# Generated by infra/azure/bootstrap.sh. SAFE TO COMMIT, AND IT MUST BE: the
# deploy workflows run 'terraform init -backend-config=envs/dev.backend.hcl',
# so a git-ignored file would leave CI unable to find its own state. Nothing
# here is a secret -- these are resource names, and authentication is the OIDC
# token the workflow already holds.
#
#   terraform init -backend-config=envs/dev.backend.hcl
resource_group_name  = "rg-firmaware-tfstate"
storage_account_name = "stfirmawaretffa7k"
container_name       = "tfstate-dev"
key                  = "firmaware-dev.tfstate"
